### ISSUE TITLE
Why depend both resteasy-jackson and reasteasy-jsonb?

### ISSUE THREAD

**Issue by rainmanhhh** [fmcejudo/quarkus-eureka#13]
should it be only one of them?

**Comment by fmcejudo** [comment]
you might be right. I guess this should be enough with  `resteasy-jackson`. Thought I got some troubles with resteasy and more recent version of Quarkus, I am behind that problem, but I couldn't come up with any solution yet. I will give it a go. Thanks for taking a look and point to this.

**Comment by fmcejudo** [comment]
@rainmanhhh I have been checking it and you are right it depends just from `resteasy-jackson`, I am updating and upgrading some stuff. I appreciate your point. Thanks.
