### ISSUE TITLE
Some properties should have default value?

### ISSUE THREAD

**Issue by rainmanhhh** [fmcejudo/quarkus-eureka#14]
below properties are reported as required, but maybe some of them could have default value?(like springcloud eureka client)
quarkus.eureka.name=${quarkus.application.name}
quarkus.eureka.port=${quarkus.http.port}
quarkus.eureka.vip-address= <don't know what it exactly is. springcloud eureka client seems do not have this property?>
quarkus.eureka.host-name= <get from host machine like spring do>
quarkus.eureka.region=default

**Comment by fmcejudo** [comment]
Thank you very much for that, I will update this as soon as possible. Very good point!!

**Comment by rainmanhhh** [comment]
btw, sugguest to use /eureka/info instead of /info as default root path(for eureka health check) to make it more clearly different from other business paths

**Comment by fmcejudo** [comment]
Your idea has been already implemented in latest version 0.0.7. Thanks for that, it looks nicer and less things to attend.I left /info as this the same Spring does, but I can consider it. Why do you think is better /eureka/info?

**Comment by rainmanhhh** [comment]
spring use /info because it's a “common” health check path(not only for eureka)

**Comment by rainmanhhh** [comment]
btw, my current config:
```
    health-check-url: ${quarkus.smallrye-health.root-path:/health}
    status-page-url: ${quarkus.swagger-ui.path:/swagger-ui}
```
if this project is dedicated to eureka, /eureka/info would be a good default value;
if this project try to fit "convention of quarkus", ${quarkus.smallrye-health.root-path:/health} would be better
