### ISSUE TITLE
Add a heartbeat to the extension

### ISSUE THREAD

**Issue by dwamara** [fmcejudo/quarkus-eureka#15]
I tested the extension and found it good until I realised that once the service is registered, it will be deregistered after a certain time as eureka has to be taught.
It would be good if a heartbeat could be added to the extension that could be configurable via a property and that could, like the registration, notify eureka with the configured interval that the service is still running and there.

**Comment by fmcejudo** [comment]
thanks for the suggestion, I have to keep researching about this as there are some operations I haven’t try yet. I will research about it. Thanks for giving it a try!

**Comment by dwamara** [comment]
You could try to make another class and use the logic that you have in https://github.com/fmcejudo/quarkus-eureka/blob/master/quarkus-eureka/src/main/java/io/quarkus/eureka/registration/EurekaRegistrationService.java so that the service could check if it still is on eureka (if that's possible) and if not then it will be registered again.
