### ISSUE TITLE
dependency scope of rest-assured problem

### ISSUE THREAD

**Issue by rainmanhhh** [fmcejudo/quarkus-eureka#20]
```
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils
        at io.quarkus.eureka.config.EurekaRuntimeConfiguration$NetworkConverter.convert(EurekaRuntimeConfiguration.java:98)
```

class EurekaRuntimeConfiguration depends on org.apache.commons.lang3.StringUtils
 provided by org.apache.commons:commons-lang3:jar:3.4:provided
 provided by io.rest-assured:xml-path:jar:4.3.0:test
 provided by io.rest-assured:json-path:jar:4.3.0:test
 provided by io.rest-assured:rest-assured:jar:4.3.0:test

the scope is test but not compile
suggest to change into:
```
@Override
public String convert(final String hostname) {
  if (hostname == null || hostname.isEmpty()) return HostNameDiscovery.getHostName();
  else return hostname;
}
```

**Comment by rainmanhhh** [comment]
@fmcejudo

**Comment by fmcejudo** [comment]
I have already done it in that way, I will release it today or tomorrow. Thank you @rainmanhhh for spotting those issues.

**Comment by fmcejudo** [comment]
@rainmanhhh deployed version 0.0.8. Thaks!!
