### ISSUE TITLE
can not work

### ISSUE THREAD

**Issue by linking12** [fmcejudo/quarkus-eureka#25]
```
quarkus.http.port=8080
quarkus.application.name=quarkus-sample
quarkus.eureka.region=default
quarkus.eureka.prefer-same-zone=true
quarkus.eureka.should-use-dns=false
quarkus.eureka.service-url.default=http:/localhost:8761/eureka
```

Only config in properties, but can not work, app can not register in eureka;
May be I miss something others?

**Comment by fmcejudo** [comment]
Hi @linking12 . did you get any log with more info? Off the top of my head I can't find any issue with that config. 
Also, if you want to, you can compare with an example I did on github:

https://github.com/currofy/coffee-shop-parent

But if you have more logs we can try to work that out

**Comment by linking12** [comment]
> Hi @linking12 . did you get any log with more info? Off the top of my head I can't find any issue with that config.
> Also, if you want to, you can compare with an example I did on github:
> 
> https://github.com/currofy/coffee-shop-parent
> 
> But if you have more logs we can try to work that out

Thank you for your quickly reply, It is my fault for I miss provide health endpoint
