### ISSUE TITLE
Add enabled configuration parameter

### ISSUE THREAD

**Issue by tobi6112** [fmcejudo/quarkus-eureka#28]
I would like to enable the eureka client only when the prod-profile is enabled, when dev mode is active it should not be running.

Is it possible to add a configuration parameter to enable the eureka client? For example:
```properties
quarkus.eureka.enable=false
%prod.quarkus.eureka.enable=true
```
The parameter should use `true` as default value.

**Comment by fmcejudo** [comment]
@tobi6112 sure, we can do that!
