### ISSUE TITLE
Conflict with quarkus-resteasy-reactive

### ISSUE THREAD

**Issue by angelo147** [fmcejudo/quarkus-eureka#32]
When using quarkus-eureka with quarkus-resteasy-reactive app cannot start with the following error:

Multiple matching properties for name "security.jaxrs.deny-unannotated-endpoints" property was matched by both public boolean io.quarkus.resteasy.runtime.JaxRsSecurityConfig.denyJaxRs and public boolean io.quarkus.resteasy.reactive.common.runtime.JaxRsSecurityConfig.denyJaxRs. This is likely because you have an incompatible combination of extensions that both define the same properties (e.g. including both reactive and blocking database extensions)

Can we somehow overcome this?

**Comment by fmcejudo** [comment]
Hi, do you have any repo with this failing to give it a try? though I have pushed a branch `try_without_rest_easy` a dependency `quarkus-resteasy` which is seemed it is not used. 

Can you pull the branch `mvn clean install` and try with version 0.0.13-SNAPSHOT? 
If you have other ideas to test this, please let me know

**Comment by angelo147** [comment]
Hello, the #33 pr changes solved my conflict issues. You can close the issue whenever you think is ok for you.
