### ISSUE TITLE
eurekaClient not using contextPath

### ISSUE THREAD

**Issue by najibk** [fmcejudo/quarkus-eureka#35]
Hello,

eurekaClient does not take into account the basePath which can be found in eureka response : instance.metadata.context
without this context, all requests sent by eurekaClient are invalid.

Is this something that could be done in an upcoming release ? 

Thanks

**Comment by fmcejudo** [comment]
Hi @najibk, sure. At least I can give it a try. So, if I am right, you mean that the property you mention above is required, else the Eureka client fails.

I will try to tests that use case and find a solution for it. Thanks for reporting it

**Comment by najibk** [comment]
@fmcejudo thanks for the quick reply !

Yes, the property is the equivalent of basePath in swagger 2.0 specs (https://swagger.io/docs/specification/2-0/api-host-and-base-path/), requesting an endpoint without supplying the proper full url just results in a 404 responses because of the missing piece (basePath).
for example, given this specs : https://petstore.swagger.io/v2/swagger.json
- eureka server would reply with instance.hostName: petstore.swagger.io and instance.metadata.context: v2
- eurekaClient would request http://petstore.swagger.io/pet/findByStatus instead of http://petstore.swagger.io/**v2**/pet/findByStatus

**Comment by fmcejudo** [comment]
hi @najibk , you can find that feature done in https://github.com/fmcejudo/quarkus-eureka/tree/instance_base_path 

I have to cover this with some tests and then I will release it. But just in case you want to play with it locally.

Thanks for reporting this, I didn’t know even that feature was there. I will let you know when released, hopefully middle next week.

Have a good weekend. Cheers

**Comment by najibk** [comment]
hello @fmcejudo,
I noticed the java version bump, it is worth mentioning in the docs I think, other than that it seems to be working as expected !
Thanks again and have a nice weekend.

**Comment by fmcejudo** [comment]
@najibk this issue has been amended in the 0.0.14 released yesterday. Can you give it a try, check and close the issue if fixed? If it does not meet the requirement or you find something else, please don't hesitate to contact and I will be more than happy to code a bit more ;)
