### ISSUE TITLE
Improve debug / ease configuration with logs

### ISSUE THREAD

**Issue by sebastienpayet** [fmcejudo/quarkus-eureka#39]
Hi,

I use your lib as a dependance in a **_native_** quarkus project, embedded in a Docker container.

In this configuration, i face following problem :  the eureka client of my application never found a targeted instance, the appId "XXX" was never found.

**Cause**: The true problem (com.fasterxml.jackson.databind.exc.InvalidDefinitionException) was hidden by a too wide exception catch : 
MultipleInstanceQueryOperation.findInstance

`try {
            final String path = String.join("/", "apps", appId);
            return query(location, path, ApplicationResult.class);
        } catch(Exception e) {
            return ApplicationResult.error();
        }`

I found and fix the error by embedding all of you code in my project, so i was able to add some logs to find the real problem.

**Solution**: add a @RegisterForReflection(targets={ ApplicationResult.class, InstanceResult.class}) configuration class in my app, has the official documentation mention it  [quarkus doc](https://quarkus.io/guides/writing-native-applications-tips).
I'am pretty new to quarkus, so a better solution maybe more obvious for experienced users.

So the problem is not directly related to the library, but i think we can make some improvements. 

**Suggestion** : add some logs on this kind of catch, to give more infos, especially if the parent application is used in native mode.

I would be happy to make pull request on this.

**Comment by fmcejudo** [comment]
Hi @sebastienpayet ,

Thanks for using it and more than welcome to include your ideas what makes it better.

I have never seen the problem before, so you can do the appropriated changes to evolve it and cover more.

Cheers.
