### ISSUE TITLE
Extended support to notify the server when the service is offline

### ISSUE THREAD

**Issue by janyyy** [fmcejudo/quarkus-eureka#40]
During use, I found that after I closed the program, the Eurake server did not mark the service as DOWN. Has it not been implemented yet?

**Comment by fmcejudo** [comment]
Hi @janyyy , it should deregister the application on stop event.

https://github.com/fmcejudo/quarkus-eureka/blob/master/quarkus-eureka/src/main/java/io/quarkus/eureka/EurekaProducer.java#L76

But I am not sure if the application stops abruptly, if this event is still triggered.

I can check that or try to implement another mechanism to ensure this method is called.

Cheers.

**Comment by janyyy** [comment]
Hi @fmcejudo 
I'll test it for you .

**Comment by janyyy** [comment]
@fmcejudo 
The kill command can be removed, but kill -9 doesn't seem to work. thanks
