### ISSUE TITLE
Framework restclient is not closed log problem

### ISSUE THREAD

**Issue by janyyy** [fmcejudo/quarkus-eureka#42]
@fmcejudo 
Hi, fmcejudo
I am now using the Quarkus framework version 3.9.0, and found WARN logs when using eurake for high availability of services.
`WARN  [org.jbo.res.cli.jax.i18n] (Finalizer) RESTEASY004687: Closing a class org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient43Engine instance for you. Please close clients yourself.`
 I also found the same problem in other modules. It's fine to inherit the `AutoCloseable` interface in the RestClient class. When will this problem be fixed?
![image](https://user-images.githubusercontent.com/27274865/170674001-67096f31-5f64-460d-be6c-05c75fe1d5a7.png)

**Comment by framcejudo** [comment]
Hi @janyyy , I will try to invest some time next week reviewing this error. Let's see how it goes
