### ISSUE TITLE
Additional metadata

### ISSUE THREAD

**Issue by efrancis59** [fmcejudo/quarkus-eureka#43]
Hello, 
Is it possible to configure more instance metadata to be registered in eureka server ? Currently, the unique registered metadata is "context". 

If it is not possible to be done by configuration, how can we do it programmatically ?

**Comment by fmcejudo** [comment]
Hi @efrancis59 , I am not sure if I got the idea, you want to send more metadata to eureka server? Can you give more details, please?

**Comment by fmcejudo** [comment]
Ok, thanks! I have never used this feature before. I guess this is something I have to send when registering application. I will take a look!

**Comment by fmcejudo** [comment]
you were right, by adding metadata  map, you can see that in Eureka registry JHipster flavour, I didn't appreciate that in the Eureka I used.

Please, check the PR and if you agree I will merge it

<img width="1391" alt="Screenshot 2022-09-18 at 01 25 31" src="https://user-images.githubusercontent.com/12185075/190879482-0a00c304-3243-4e96-9ab1-fc16b0c987b7.png">
<img width="454" alt="Screenshot 2022-09-18 at 01 25 47" src="https://user-images.githubusercontent.com/12185075/190879484-a2328ab5-dd68-4fa1-ba7a-a8598bce0785.png">

Thanks for your  issue and your time

**Comment by efrancis59** [comment]
Very good solution.
Thank you.

**Comment by fmcejudo** [comment]
Great. Thanks. I will release it this week. For now, you can build it locally and use 0.0.15-SNAPSHOT.
