### ISSUE TITLE
RESTEASY003215: could not find writer for content-type multipart/form-data type

### ISSUE THREAD

**Issue by janyyy** [fmcejudo/quarkus-eureka#52]
I hava a interface about file upload requirment, but had some error, can you give me some advie ?
![image](https://user-images.githubusercontent.com/27274865/230872623-d9720f49-50ac-456e-ae6f-5e56a06dd322.png)
![image](https://user-images.githubusercontent.com/27274865/230872702-45c5a5c1-96bf-49bd-a94c-5dae3117a859.png)

the UploadEntity Class content like these
![image](https://user-images.githubusercontent.com/27274865/230872904-68729b4a-db86-43fa-8bbb-346583d77663.png)

**Comment by fmcejudo** [comment]
Hi @janyyy , not sure about that. But we might try upgrading `resteasy` or trying to include a writer if so to the project.

**Comment by janyyy** [comment]
Dear @fmcejudo , looking forward to your good news.
