### ISSUE TITLE
Can we please use: quarkus-rest-client-reactive over quarkus-rest-client

### ISSUE THREAD

**Issue by maranza** [fmcejudo/quarkus-eureka#62]
It is now recommended by quarkus that we use the quarkus-rest-client-reactive over quarkus-rest-client as the reactive dependency offers more functionality and is compatible with the functionality already existing within quarkus-rest-client.

I would like to contribute this but i am not sure how i can build this project, I will be trying though in the meantime. Thanks

below is the error when trying to use this dependency on a project that uses quarkus-rest-client-reactive:

Failed to build quarkus application: Failed to load steps from class io.quarkus.restclient.deployment.RestClientProcessor

**Comment by fmcejudo** [comment]
Thanks for that! It is a great idea to go ahead. I have merged it to develop now! I will check it works properly and I will do the release as soon as possible. Thanks for the support!

**Comment by fmcejudo** [comment]
I close this, as the dependency has been renamed, as follow in coming documentation:


https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.9#resteasy-reactive-extensions-renamed-to-quarkus-rest-gear-white_check_mark
